openapi: 3.0.3
info:
  title: API Reference | ReDoc
  version: 1.0.0
  description: API для керування контактами та аутентифікації користувачів
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://nodejs-hw-mongodb-5okd.onrender.com

tags:
  - name: auth
    description: Операції, пов'язані з аутентифікацією користувачів
  - name: contacts
    description: Операції з контактами користувачів
  - name: general
    description: Загальні ендпоінти

paths:
  /:
    $ref: ./swagger/paths/root.yaml

  /auth/register:
    $ref: ./swagger/paths/auth_paths/register.yaml

  /auth/login:
    $ref: ./swagger/paths/auth_paths/login.yaml

  /auth/refresh:
    $ref: ./swagger/paths/auth_paths/refresh.yaml

  /auth/logout:
    $ref: ./swagger/paths/auth_paths/logout.yaml

  /auth/send-reset-email:
    $ref: ./swagger/paths/auth_paths/send_reset_email.yaml

  /auth/reset-pwd:
    $ref: ./swagger/paths/auth_paths/reset_pwd.yaml

  /contacts:
    $ref: ./swagger/paths/contacts/index.yaml

  /contacts/{contactId}:
    parameters:
      - name: contactId
        in: path
        required: true
        schema:
          type: string
          description: Ідентифікатор контакту
    get:
      $ref: ./swagger/paths/contacts/contact_id/get_contact_by_id.yaml
    patch:
      $ref: ./swagger/paths/contacts/contact_id/update_contact.yaml
    delete:
      $ref: ./swagger/paths/contacts/contact_id/delete_contact.yaml

components:
  schemas:
    Contact:
      $ref: ./swagger/components/schemas/Contact.yaml
    User:
      $ref: ./swagger/components/schemas/User.yaml
    Session:
      $ref: ./swagger/components/schemas/Session.yaml
    ErrorResponse:
      $ref: ./swagger/components/schemas/error_response.yaml

  responses:
    SuccessResponse:
      $ref: ./swagger/components/responses/success_response.yaml
    ErrorResponse:
      $ref: ./swagger/components/responses/error_response.yaml

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []